### ISSUE TITLE
如果密钥包含 url 和 `/com`，它就会变成 `,`。

### ISSUE THREAD

**Issue by yupix** [LorisYounger/LinePutScript#1]
以下代码用于读入 VPet 翻译文件，使用 `ToString()` 进行编辑并输出。 在这种情况下，`Sub.TextDeReplace` 用于恢复已被内部替换为 `/com` 等的原始文件。 在这种情况下，我遇到了麻烦，因为如果在 URL 等中包含 `/com`，它就会被 `,`替换。 有什么解决办法吗？

## 有问题密钥的 URL
https://github.com/LorisYounger/VPet/blob/main/VPet-Simulator.Windows/mod/0000_core/lang/zh-Hans/Base2306.lps#L246

## 代码摘录

```csharp
var lps = new LpsDocument(File.ReadAllText(filePath));
// 某种操纵
File.WriteAllText(exportFilePath, Sub.TextDeReplace(lps.ToString()));
```

**Comment by LorisYounger** [comment]
转义下, 用 /! 代替/

**Comment by yupix** [comment]
这是关于转义 `Line.Value`吗？我想问的是，如果 `Line.Name` 包含 `/com`，那么在 `LpsDocument.ToString()` ``Sub.TextDeReplace` 之后，即使 `Line.Name` 中的字符也会返回为 `,`。 如果有任何差异，我深表歉意。 如果是我自己的项目，我会更改键值，但在这种情况下，我不想做任何更改，因为我使用的是 VPet 语言文件。

代码执行后的文件更改
```diff
-API 链接 一般为 api.openai.com/v1/chat/completions#API 链接 一般为 api.openai.com/v1/chat/!completions:|
+API 链接 一般为 api.openai.com/v1/chat,pletions#API 链接 一般为 api.openai.com/v1/chat/!completions:|
